// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: prometheus.proto

package io.prometheus.client;

public final class Prometheus {
  private Prometheus() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface LabelOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string key = 1;
    /**
     * <code>optional string key = 1;</code>
     */
    boolean hasKey();
    /**
     * <code>optional string key = 1;</code>
     */
    java.lang.String getKey();
    /**
     * <code>optional string key = 1;</code>
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    // optional string val = 2;
    /**
     * <code>optional string val = 2;</code>
     */
    boolean hasVal();
    /**
     * <code>optional string val = 2;</code>
     */
    java.lang.String getVal();
    /**
     * <code>optional string val = 2;</code>
     */
    com.google.protobuf.ByteString
        getValBytes();
  }
  /**
   * Protobuf type {@code io.prometheus.client.Label}
   */
  public static final class Label extends
      com.google.protobuf.GeneratedMessage
      implements LabelOrBuilder {
    // Use Label.newBuilder() to construct.
    private Label(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Label(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Label defaultInstance;
    public static Label getDefaultInstance() {
      return defaultInstance;
    }

    public Label getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Label(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              key_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              val_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.prometheus.client.Prometheus.internal_static_io_prometheus_client_Label_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.prometheus.client.Prometheus.internal_static_io_prometheus_client_Label_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.prometheus.client.Prometheus.Label.class, io.prometheus.client.Prometheus.Label.Builder.class);
    }

    public static com.google.protobuf.Parser<Label> PARSER =
        new com.google.protobuf.AbstractParser<Label>() {
      public Label parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Label(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Label> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string key = 1;
    public static final int KEY_FIELD_NUMBER = 1;
    private java.lang.Object key_;
    /**
     * <code>optional string key = 1;</code>
     */
    public boolean hasKey() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string key = 1;</code>
     */
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          key_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string key = 1;</code>
     */
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string val = 2;
    public static final int VAL_FIELD_NUMBER = 2;
    private java.lang.Object val_;
    /**
     * <code>optional string val = 2;</code>
     */
    public boolean hasVal() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string val = 2;</code>
     */
    public java.lang.String getVal() {
      java.lang.Object ref = val_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          val_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string val = 2;</code>
     */
    public com.google.protobuf.ByteString
        getValBytes() {
      java.lang.Object ref = val_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        val_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      key_ = "";
      val_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getKeyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getValBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getKeyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getValBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static io.prometheus.client.Prometheus.Label parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.prometheus.client.Prometheus.Label parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.prometheus.client.Prometheus.Label parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.prometheus.client.Prometheus.Label parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.prometheus.client.Prometheus.Label parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static io.prometheus.client.Prometheus.Label parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static io.prometheus.client.Prometheus.Label parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static io.prometheus.client.Prometheus.Label parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static io.prometheus.client.Prometheus.Label parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static io.prometheus.client.Prometheus.Label parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(io.prometheus.client.Prometheus.Label prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code io.prometheus.client.Label}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements io.prometheus.client.Prometheus.LabelOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.prometheus.client.Prometheus.internal_static_io_prometheus_client_Label_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.prometheus.client.Prometheus.internal_static_io_prometheus_client_Label_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.prometheus.client.Prometheus.Label.class, io.prometheus.client.Prometheus.Label.Builder.class);
      }

      // Construct using io.prometheus.client.Prometheus.Label.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        key_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        val_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.prometheus.client.Prometheus.internal_static_io_prometheus_client_Label_descriptor;
      }

      public io.prometheus.client.Prometheus.Label getDefaultInstanceForType() {
        return io.prometheus.client.Prometheus.Label.getDefaultInstance();
      }

      public io.prometheus.client.Prometheus.Label build() {
        io.prometheus.client.Prometheus.Label result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public io.prometheus.client.Prometheus.Label buildPartial() {
        io.prometheus.client.Prometheus.Label result = new io.prometheus.client.Prometheus.Label(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.key_ = key_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.val_ = val_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.prometheus.client.Prometheus.Label) {
          return mergeFrom((io.prometheus.client.Prometheus.Label)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.prometheus.client.Prometheus.Label other) {
        if (other == io.prometheus.client.Prometheus.Label.getDefaultInstance()) return this;
        if (other.hasKey()) {
          bitField0_ |= 0x00000001;
          key_ = other.key_;
          onChanged();
        }
        if (other.hasVal()) {
          bitField0_ |= 0x00000002;
          val_ = other.val_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.prometheus.client.Prometheus.Label parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.prometheus.client.Prometheus.Label) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string key = 1;
      private java.lang.Object key_ = "";
      /**
       * <code>optional string key = 1;</code>
       */
      public boolean hasKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string key = 1;</code>
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          key_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string key = 1;</code>
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string key = 1;</code>
       */
      public Builder setKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string key = 1;</code>
       */
      public Builder clearKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      /**
       * <code>optional string key = 1;</code>
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
        return this;
      }

      // optional string val = 2;
      private java.lang.Object val_ = "";
      /**
       * <code>optional string val = 2;</code>
       */
      public boolean hasVal() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string val = 2;</code>
       */
      public java.lang.String getVal() {
        java.lang.Object ref = val_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          val_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string val = 2;</code>
       */
      public com.google.protobuf.ByteString
          getValBytes() {
        java.lang.Object ref = val_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          val_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string val = 2;</code>
       */
      public Builder setVal(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        val_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string val = 2;</code>
       */
      public Builder clearVal() {
        bitField0_ = (bitField0_ & ~0x00000002);
        val_ = getDefaultInstance().getVal();
        onChanged();
        return this;
      }
      /**
       * <code>optional string val = 2;</code>
       */
      public Builder setValBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        val_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:io.prometheus.client.Label)
    }

    static {
      defaultInstance = new Label(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:io.prometheus.client.Label)
  }

  public interface SampleOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string name = 1;
    /**
     * <code>optional string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>optional string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // optional double value = 2;
    /**
     * <code>optional double value = 2;</code>
     */
    boolean hasValue();
    /**
     * <code>optional double value = 2;</code>
     */
    double getValue();

    // optional int64 time = 3;
    /**
     * <code>optional int64 time = 3;</code>
     *
     * <pre>
     * Optional timestamp, in seconds since the epoch.
     *
     * By default, samples are timestamped by a prometheus server at the time of
     * collection.
     *
     * Certain clients, however, may want to provide their own time for a sample.
     * For example, a client which polls an external resource on certain
     * invtervals to produce samples may wish to assign the time of the last poll
     * to its samples.
     * </pre>
     */
    boolean hasTime();
    /**
     * <code>optional int64 time = 3;</code>
     *
     * <pre>
     * Optional timestamp, in seconds since the epoch.
     *
     * By default, samples are timestamped by a prometheus server at the time of
     * collection.
     *
     * Certain clients, however, may want to provide their own time for a sample.
     * For example, a client which polls an external resource on certain
     * invtervals to produce samples may wish to assign the time of the last poll
     * to its samples.
     * </pre>
     */
    long getTime();

    // repeated .io.prometheus.client.Label label = 4;
    /**
     * <code>repeated .io.prometheus.client.Label label = 4;</code>
     */
    java.util.List<io.prometheus.client.Prometheus.Label> 
        getLabelList();
    /**
     * <code>repeated .io.prometheus.client.Label label = 4;</code>
     */
    io.prometheus.client.Prometheus.Label getLabel(int index);
    /**
     * <code>repeated .io.prometheus.client.Label label = 4;</code>
     */
    int getLabelCount();
    /**
     * <code>repeated .io.prometheus.client.Label label = 4;</code>
     */
    java.util.List<? extends io.prometheus.client.Prometheus.LabelOrBuilder> 
        getLabelOrBuilderList();
    /**
     * <code>repeated .io.prometheus.client.Label label = 4;</code>
     */
    io.prometheus.client.Prometheus.LabelOrBuilder getLabelOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code io.prometheus.client.Sample}
   *
   * <pre>
   * Prometheus clients are expected to produce a varint-encoded length-delimited
   * massage stream.
   *
   * Clients are also encouraged to provide a human-accessible endpoint
   * which displays the samples it is emitting, as well as some
   * documentation about what the values represent.
   * </pre>
   */
  public static final class Sample extends
      com.google.protobuf.GeneratedMessage
      implements SampleOrBuilder {
    // Use Sample.newBuilder() to construct.
    private Sample(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Sample(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Sample defaultInstance;
    public static Sample getDefaultInstance() {
      return defaultInstance;
    }

    public Sample getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Sample(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              value_ = input.readDouble();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              time_ = input.readInt64();
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                label_ = new java.util.ArrayList<io.prometheus.client.Prometheus.Label>();
                mutable_bitField0_ |= 0x00000008;
              }
              label_.add(input.readMessage(io.prometheus.client.Prometheus.Label.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          label_ = java.util.Collections.unmodifiableList(label_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.prometheus.client.Prometheus.internal_static_io_prometheus_client_Sample_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.prometheus.client.Prometheus.internal_static_io_prometheus_client_Sample_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.prometheus.client.Prometheus.Sample.class, io.prometheus.client.Prometheus.Sample.Builder.class);
    }

    public static com.google.protobuf.Parser<Sample> PARSER =
        new com.google.protobuf.AbstractParser<Sample>() {
      public Sample parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Sample(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Sample> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    /**
     * <code>optional string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional double value = 2;
    public static final int VALUE_FIELD_NUMBER = 2;
    private double value_;
    /**
     * <code>optional double value = 2;</code>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional double value = 2;</code>
     */
    public double getValue() {
      return value_;
    }

    // optional int64 time = 3;
    public static final int TIME_FIELD_NUMBER = 3;
    private long time_;
    /**
     * <code>optional int64 time = 3;</code>
     *
     * <pre>
     * Optional timestamp, in seconds since the epoch.
     *
     * By default, samples are timestamped by a prometheus server at the time of
     * collection.
     *
     * Certain clients, however, may want to provide their own time for a sample.
     * For example, a client which polls an external resource on certain
     * invtervals to produce samples may wish to assign the time of the last poll
     * to its samples.
     * </pre>
     */
    public boolean hasTime() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int64 time = 3;</code>
     *
     * <pre>
     * Optional timestamp, in seconds since the epoch.
     *
     * By default, samples are timestamped by a prometheus server at the time of
     * collection.
     *
     * Certain clients, however, may want to provide their own time for a sample.
     * For example, a client which polls an external resource on certain
     * invtervals to produce samples may wish to assign the time of the last poll
     * to its samples.
     * </pre>
     */
    public long getTime() {
      return time_;
    }

    // repeated .io.prometheus.client.Label label = 4;
    public static final int LABEL_FIELD_NUMBER = 4;
    private java.util.List<io.prometheus.client.Prometheus.Label> label_;
    /**
     * <code>repeated .io.prometheus.client.Label label = 4;</code>
     */
    public java.util.List<io.prometheus.client.Prometheus.Label> getLabelList() {
      return label_;
    }
    /**
     * <code>repeated .io.prometheus.client.Label label = 4;</code>
     */
    public java.util.List<? extends io.prometheus.client.Prometheus.LabelOrBuilder> 
        getLabelOrBuilderList() {
      return label_;
    }
    /**
     * <code>repeated .io.prometheus.client.Label label = 4;</code>
     */
    public int getLabelCount() {
      return label_.size();
    }
    /**
     * <code>repeated .io.prometheus.client.Label label = 4;</code>
     */
    public io.prometheus.client.Prometheus.Label getLabel(int index) {
      return label_.get(index);
    }
    /**
     * <code>repeated .io.prometheus.client.Label label = 4;</code>
     */
    public io.prometheus.client.Prometheus.LabelOrBuilder getLabelOrBuilder(
        int index) {
      return label_.get(index);
    }

    private void initFields() {
      name_ = "";
      value_ = 0D;
      time_ = 0L;
      label_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(2, value_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, time_);
      }
      for (int i = 0; i < label_.size(); i++) {
        output.writeMessage(4, label_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, value_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, time_);
      }
      for (int i = 0; i < label_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, label_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static io.prometheus.client.Prometheus.Sample parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.prometheus.client.Prometheus.Sample parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.prometheus.client.Prometheus.Sample parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.prometheus.client.Prometheus.Sample parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.prometheus.client.Prometheus.Sample parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static io.prometheus.client.Prometheus.Sample parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static io.prometheus.client.Prometheus.Sample parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static io.prometheus.client.Prometheus.Sample parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static io.prometheus.client.Prometheus.Sample parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static io.prometheus.client.Prometheus.Sample parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(io.prometheus.client.Prometheus.Sample prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code io.prometheus.client.Sample}
     *
     * <pre>
     * Prometheus clients are expected to produce a varint-encoded length-delimited
     * massage stream.
     *
     * Clients are also encouraged to provide a human-accessible endpoint
     * which displays the samples it is emitting, as well as some
     * documentation about what the values represent.
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements io.prometheus.client.Prometheus.SampleOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.prometheus.client.Prometheus.internal_static_io_prometheus_client_Sample_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.prometheus.client.Prometheus.internal_static_io_prometheus_client_Sample_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.prometheus.client.Prometheus.Sample.class, io.prometheus.client.Prometheus.Sample.Builder.class);
      }

      // Construct using io.prometheus.client.Prometheus.Sample.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getLabelFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        value_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        time_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        if (labelBuilder_ == null) {
          label_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          labelBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.prometheus.client.Prometheus.internal_static_io_prometheus_client_Sample_descriptor;
      }

      public io.prometheus.client.Prometheus.Sample getDefaultInstanceForType() {
        return io.prometheus.client.Prometheus.Sample.getDefaultInstance();
      }

      public io.prometheus.client.Prometheus.Sample build() {
        io.prometheus.client.Prometheus.Sample result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public io.prometheus.client.Prometheus.Sample buildPartial() {
        io.prometheus.client.Prometheus.Sample result = new io.prometheus.client.Prometheus.Sample(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.value_ = value_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.time_ = time_;
        if (labelBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            label_ = java.util.Collections.unmodifiableList(label_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.label_ = label_;
        } else {
          result.label_ = labelBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.prometheus.client.Prometheus.Sample) {
          return mergeFrom((io.prometheus.client.Prometheus.Sample)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.prometheus.client.Prometheus.Sample other) {
        if (other == io.prometheus.client.Prometheus.Sample.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        if (other.hasTime()) {
          setTime(other.getTime());
        }
        if (labelBuilder_ == null) {
          if (!other.label_.isEmpty()) {
            if (label_.isEmpty()) {
              label_ = other.label_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureLabelIsMutable();
              label_.addAll(other.label_);
            }
            onChanged();
          }
        } else {
          if (!other.label_.isEmpty()) {
            if (labelBuilder_.isEmpty()) {
              labelBuilder_.dispose();
              labelBuilder_ = null;
              label_ = other.label_;
              bitField0_ = (bitField0_ & ~0x00000008);
              labelBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getLabelFieldBuilder() : null;
            } else {
              labelBuilder_.addAllMessages(other.label_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.prometheus.client.Prometheus.Sample parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.prometheus.client.Prometheus.Sample) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string name = 1;
      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      // optional double value = 2;
      private double value_ ;
      /**
       * <code>optional double value = 2;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional double value = 2;</code>
       */
      public double getValue() {
        return value_;
      }
      /**
       * <code>optional double value = 2;</code>
       */
      public Builder setValue(double value) {
        bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double value = 2;</code>
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = 0D;
        onChanged();
        return this;
      }

      // optional int64 time = 3;
      private long time_ ;
      /**
       * <code>optional int64 time = 3;</code>
       *
       * <pre>
       * Optional timestamp, in seconds since the epoch.
       *
       * By default, samples are timestamped by a prometheus server at the time of
       * collection.
       *
       * Certain clients, however, may want to provide their own time for a sample.
       * For example, a client which polls an external resource on certain
       * invtervals to produce samples may wish to assign the time of the last poll
       * to its samples.
       * </pre>
       */
      public boolean hasTime() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int64 time = 3;</code>
       *
       * <pre>
       * Optional timestamp, in seconds since the epoch.
       *
       * By default, samples are timestamped by a prometheus server at the time of
       * collection.
       *
       * Certain clients, however, may want to provide their own time for a sample.
       * For example, a client which polls an external resource on certain
       * invtervals to produce samples may wish to assign the time of the last poll
       * to its samples.
       * </pre>
       */
      public long getTime() {
        return time_;
      }
      /**
       * <code>optional int64 time = 3;</code>
       *
       * <pre>
       * Optional timestamp, in seconds since the epoch.
       *
       * By default, samples are timestamped by a prometheus server at the time of
       * collection.
       *
       * Certain clients, however, may want to provide their own time for a sample.
       * For example, a client which polls an external resource on certain
       * invtervals to produce samples may wish to assign the time of the last poll
       * to its samples.
       * </pre>
       */
      public Builder setTime(long value) {
        bitField0_ |= 0x00000004;
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 time = 3;</code>
       *
       * <pre>
       * Optional timestamp, in seconds since the epoch.
       *
       * By default, samples are timestamped by a prometheus server at the time of
       * collection.
       *
       * Certain clients, however, may want to provide their own time for a sample.
       * For example, a client which polls an external resource on certain
       * invtervals to produce samples may wish to assign the time of the last poll
       * to its samples.
       * </pre>
       */
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000004);
        time_ = 0L;
        onChanged();
        return this;
      }

      // repeated .io.prometheus.client.Label label = 4;
      private java.util.List<io.prometheus.client.Prometheus.Label> label_ =
        java.util.Collections.emptyList();
      private void ensureLabelIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          label_ = new java.util.ArrayList<io.prometheus.client.Prometheus.Label>(label_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          io.prometheus.client.Prometheus.Label, io.prometheus.client.Prometheus.Label.Builder, io.prometheus.client.Prometheus.LabelOrBuilder> labelBuilder_;

      /**
       * <code>repeated .io.prometheus.client.Label label = 4;</code>
       */
      public java.util.List<io.prometheus.client.Prometheus.Label> getLabelList() {
        if (labelBuilder_ == null) {
          return java.util.Collections.unmodifiableList(label_);
        } else {
          return labelBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .io.prometheus.client.Label label = 4;</code>
       */
      public int getLabelCount() {
        if (labelBuilder_ == null) {
          return label_.size();
        } else {
          return labelBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .io.prometheus.client.Label label = 4;</code>
       */
      public io.prometheus.client.Prometheus.Label getLabel(int index) {
        if (labelBuilder_ == null) {
          return label_.get(index);
        } else {
          return labelBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .io.prometheus.client.Label label = 4;</code>
       */
      public Builder setLabel(
          int index, io.prometheus.client.Prometheus.Label value) {
        if (labelBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLabelIsMutable();
          label_.set(index, value);
          onChanged();
        } else {
          labelBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .io.prometheus.client.Label label = 4;</code>
       */
      public Builder setLabel(
          int index, io.prometheus.client.Prometheus.Label.Builder builderForValue) {
        if (labelBuilder_ == null) {
          ensureLabelIsMutable();
          label_.set(index, builderForValue.build());
          onChanged();
        } else {
          labelBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .io.prometheus.client.Label label = 4;</code>
       */
      public Builder addLabel(io.prometheus.client.Prometheus.Label value) {
        if (labelBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLabelIsMutable();
          label_.add(value);
          onChanged();
        } else {
          labelBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .io.prometheus.client.Label label = 4;</code>
       */
      public Builder addLabel(
          int index, io.prometheus.client.Prometheus.Label value) {
        if (labelBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLabelIsMutable();
          label_.add(index, value);
          onChanged();
        } else {
          labelBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .io.prometheus.client.Label label = 4;</code>
       */
      public Builder addLabel(
          io.prometheus.client.Prometheus.Label.Builder builderForValue) {
        if (labelBuilder_ == null) {
          ensureLabelIsMutable();
          label_.add(builderForValue.build());
          onChanged();
        } else {
          labelBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .io.prometheus.client.Label label = 4;</code>
       */
      public Builder addLabel(
          int index, io.prometheus.client.Prometheus.Label.Builder builderForValue) {
        if (labelBuilder_ == null) {
          ensureLabelIsMutable();
          label_.add(index, builderForValue.build());
          onChanged();
        } else {
          labelBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .io.prometheus.client.Label label = 4;</code>
       */
      public Builder addAllLabel(
          java.lang.Iterable<? extends io.prometheus.client.Prometheus.Label> values) {
        if (labelBuilder_ == null) {
          ensureLabelIsMutable();
          super.addAll(values, label_);
          onChanged();
        } else {
          labelBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .io.prometheus.client.Label label = 4;</code>
       */
      public Builder clearLabel() {
        if (labelBuilder_ == null) {
          label_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          labelBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .io.prometheus.client.Label label = 4;</code>
       */
      public Builder removeLabel(int index) {
        if (labelBuilder_ == null) {
          ensureLabelIsMutable();
          label_.remove(index);
          onChanged();
        } else {
          labelBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .io.prometheus.client.Label label = 4;</code>
       */
      public io.prometheus.client.Prometheus.Label.Builder getLabelBuilder(
          int index) {
        return getLabelFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .io.prometheus.client.Label label = 4;</code>
       */
      public io.prometheus.client.Prometheus.LabelOrBuilder getLabelOrBuilder(
          int index) {
        if (labelBuilder_ == null) {
          return label_.get(index);  } else {
          return labelBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .io.prometheus.client.Label label = 4;</code>
       */
      public java.util.List<? extends io.prometheus.client.Prometheus.LabelOrBuilder> 
           getLabelOrBuilderList() {
        if (labelBuilder_ != null) {
          return labelBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(label_);
        }
      }
      /**
       * <code>repeated .io.prometheus.client.Label label = 4;</code>
       */
      public io.prometheus.client.Prometheus.Label.Builder addLabelBuilder() {
        return getLabelFieldBuilder().addBuilder(
            io.prometheus.client.Prometheus.Label.getDefaultInstance());
      }
      /**
       * <code>repeated .io.prometheus.client.Label label = 4;</code>
       */
      public io.prometheus.client.Prometheus.Label.Builder addLabelBuilder(
          int index) {
        return getLabelFieldBuilder().addBuilder(
            index, io.prometheus.client.Prometheus.Label.getDefaultInstance());
      }
      /**
       * <code>repeated .io.prometheus.client.Label label = 4;</code>
       */
      public java.util.List<io.prometheus.client.Prometheus.Label.Builder> 
           getLabelBuilderList() {
        return getLabelFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          io.prometheus.client.Prometheus.Label, io.prometheus.client.Prometheus.Label.Builder, io.prometheus.client.Prometheus.LabelOrBuilder> 
          getLabelFieldBuilder() {
        if (labelBuilder_ == null) {
          labelBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              io.prometheus.client.Prometheus.Label, io.prometheus.client.Prometheus.Label.Builder, io.prometheus.client.Prometheus.LabelOrBuilder>(
                  label_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          label_ = null;
        }
        return labelBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:io.prometheus.client.Sample)
    }

    static {
      defaultInstance = new Sample(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:io.prometheus.client.Sample)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_io_prometheus_client_Label_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_io_prometheus_client_Label_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_io_prometheus_client_Sample_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_io_prometheus_client_Sample_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020prometheus.proto\022\024io.prometheus.client" +
      "\"!\n\005Label\022\013\n\003key\030\001 \001(\t\022\013\n\003val\030\002 \001(\t\"_\n\006S" +
      "ample\022\014\n\004name\030\001 \001(\t\022\r\n\005value\030\002 \001(\001\022\014\n\004ti" +
      "me\030\003 \001(\003\022*\n\005label\030\004 \003(\0132\033.io.prometheus." +
      "client.LabelB\035\n\024io.prometheus.clientZ\005mo" +
      "del"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_io_prometheus_client_Label_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_io_prometheus_client_Label_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_io_prometheus_client_Label_descriptor,
              new java.lang.String[] { "Key", "Val", });
          internal_static_io_prometheus_client_Sample_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_io_prometheus_client_Sample_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_io_prometheus_client_Sample_descriptor,
              new java.lang.String[] { "Name", "Value", "Time", "Label", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
