// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metrics.proto

#ifndef PROTOBUF_metrics_2eproto__INCLUDED
#define PROTOBUF_metrics_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace io {
namespace prometheus {
namespace client {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_metrics_2eproto();
void protobuf_AssignDesc_metrics_2eproto();
void protobuf_ShutdownFile_metrics_2eproto();

class Bucket;
class Counter;
class Gauge;
class Histogram;
class LabelPair;
class Metric;
class MetricFamily;
class Quantile;
class Summary;
class Untyped;

enum MetricType {
  COUNTER = 0,
  GAUGE = 1,
  SUMMARY = 2,
  UNTYPED = 3,
  HISTOGRAM = 4,
  MetricType_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  MetricType_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool MetricType_IsValid(int value);
const MetricType MetricType_MIN = COUNTER;
const MetricType MetricType_MAX = HISTOGRAM;
const int MetricType_ARRAYSIZE = MetricType_MAX + 1;

const ::google::protobuf::EnumDescriptor* MetricType_descriptor();
inline const ::std::string& MetricType_Name(MetricType value) {
  return ::google::protobuf::internal::NameOfEnum(
    MetricType_descriptor(), value);
}
inline bool MetricType_Parse(
    const ::std::string& name, MetricType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<MetricType>(
    MetricType_descriptor(), name, value);
}
// ===================================================================

class LabelPair : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:io.prometheus.client.LabelPair) */ {
 public:
  LabelPair();
  virtual ~LabelPair();

  LabelPair(const LabelPair& from);

  inline LabelPair& operator=(const LabelPair& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LabelPair& default_instance();

  void Swap(LabelPair* other);

  // implements Message ----------------------------------------------

  inline LabelPair* New() const { return New(NULL); }

  LabelPair* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const LabelPair& from);
  void MergeFrom(const LabelPair& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(LabelPair* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string name = 1;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // optional string value = 2;
  void clear_value();
  static const int kValueFieldNumber = 2;
  const ::std::string& value() const;
  void set_value(const ::std::string& value);
  void set_value(const char* value);
  void set_value(const char* value, size_t size);
  ::std::string* mutable_value();
  ::std::string* release_value();
  void set_allocated_value(::std::string* value);

  // @@protoc_insertion_point(class_scope:io.prometheus.client.LabelPair)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::internal::ArenaStringPtr value_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_metrics_2eproto();
  friend void protobuf_AssignDesc_metrics_2eproto();
  friend void protobuf_ShutdownFile_metrics_2eproto();

  void InitAsDefaultInstance();
  static LabelPair* default_instance_;
};
// -------------------------------------------------------------------

class Gauge : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:io.prometheus.client.Gauge) */ {
 public:
  Gauge();
  virtual ~Gauge();

  Gauge(const Gauge& from);

  inline Gauge& operator=(const Gauge& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Gauge& default_instance();

  void Swap(Gauge* other);

  // implements Message ----------------------------------------------

  inline Gauge* New() const { return New(NULL); }

  Gauge* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Gauge& from);
  void MergeFrom(const Gauge& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Gauge* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional double value = 1;
  void clear_value();
  static const int kValueFieldNumber = 1;
  double value() const;
  void set_value(double value);

  // @@protoc_insertion_point(class_scope:io.prometheus.client.Gauge)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  double value_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_metrics_2eproto();
  friend void protobuf_AssignDesc_metrics_2eproto();
  friend void protobuf_ShutdownFile_metrics_2eproto();

  void InitAsDefaultInstance();
  static Gauge* default_instance_;
};
// -------------------------------------------------------------------

class Counter : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:io.prometheus.client.Counter) */ {
 public:
  Counter();
  virtual ~Counter();

  Counter(const Counter& from);

  inline Counter& operator=(const Counter& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Counter& default_instance();

  void Swap(Counter* other);

  // implements Message ----------------------------------------------

  inline Counter* New() const { return New(NULL); }

  Counter* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Counter& from);
  void MergeFrom(const Counter& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Counter* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional double value = 1;
  void clear_value();
  static const int kValueFieldNumber = 1;
  double value() const;
  void set_value(double value);

  // @@protoc_insertion_point(class_scope:io.prometheus.client.Counter)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  double value_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_metrics_2eproto();
  friend void protobuf_AssignDesc_metrics_2eproto();
  friend void protobuf_ShutdownFile_metrics_2eproto();

  void InitAsDefaultInstance();
  static Counter* default_instance_;
};
// -------------------------------------------------------------------

class Quantile : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:io.prometheus.client.Quantile) */ {
 public:
  Quantile();
  virtual ~Quantile();

  Quantile(const Quantile& from);

  inline Quantile& operator=(const Quantile& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Quantile& default_instance();

  void Swap(Quantile* other);

  // implements Message ----------------------------------------------

  inline Quantile* New() const { return New(NULL); }

  Quantile* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Quantile& from);
  void MergeFrom(const Quantile& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Quantile* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional double quantile = 1;
  void clear_quantile();
  static const int kQuantileFieldNumber = 1;
  double quantile() const;
  void set_quantile(double value);

  // optional double value = 2;
  void clear_value();
  static const int kValueFieldNumber = 2;
  double value() const;
  void set_value(double value);

  // @@protoc_insertion_point(class_scope:io.prometheus.client.Quantile)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  double quantile_;
  double value_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_metrics_2eproto();
  friend void protobuf_AssignDesc_metrics_2eproto();
  friend void protobuf_ShutdownFile_metrics_2eproto();

  void InitAsDefaultInstance();
  static Quantile* default_instance_;
};
// -------------------------------------------------------------------

class Summary : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:io.prometheus.client.Summary) */ {
 public:
  Summary();
  virtual ~Summary();

  Summary(const Summary& from);

  inline Summary& operator=(const Summary& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Summary& default_instance();

  void Swap(Summary* other);

  // implements Message ----------------------------------------------

  inline Summary* New() const { return New(NULL); }

  Summary* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Summary& from);
  void MergeFrom(const Summary& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Summary* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint64 sample_count = 1;
  void clear_sample_count();
  static const int kSampleCountFieldNumber = 1;
  ::google::protobuf::uint64 sample_count() const;
  void set_sample_count(::google::protobuf::uint64 value);

  // optional double sample_sum = 2;
  void clear_sample_sum();
  static const int kSampleSumFieldNumber = 2;
  double sample_sum() const;
  void set_sample_sum(double value);

  // repeated .io.prometheus.client.Quantile quantile = 3;
  int quantile_size() const;
  void clear_quantile();
  static const int kQuantileFieldNumber = 3;
  const ::io::prometheus::client::Quantile& quantile(int index) const;
  ::io::prometheus::client::Quantile* mutable_quantile(int index);
  ::io::prometheus::client::Quantile* add_quantile();
  ::google::protobuf::RepeatedPtrField< ::io::prometheus::client::Quantile >*
      mutable_quantile();
  const ::google::protobuf::RepeatedPtrField< ::io::prometheus::client::Quantile >&
      quantile() const;

  // @@protoc_insertion_point(class_scope:io.prometheus.client.Summary)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::uint64 sample_count_;
  double sample_sum_;
  ::google::protobuf::RepeatedPtrField< ::io::prometheus::client::Quantile > quantile_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_metrics_2eproto();
  friend void protobuf_AssignDesc_metrics_2eproto();
  friend void protobuf_ShutdownFile_metrics_2eproto();

  void InitAsDefaultInstance();
  static Summary* default_instance_;
};
// -------------------------------------------------------------------

class Untyped : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:io.prometheus.client.Untyped) */ {
 public:
  Untyped();
  virtual ~Untyped();

  Untyped(const Untyped& from);

  inline Untyped& operator=(const Untyped& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Untyped& default_instance();

  void Swap(Untyped* other);

  // implements Message ----------------------------------------------

  inline Untyped* New() const { return New(NULL); }

  Untyped* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Untyped& from);
  void MergeFrom(const Untyped& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Untyped* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional double value = 1;
  void clear_value();
  static const int kValueFieldNumber = 1;
  double value() const;
  void set_value(double value);

  // @@protoc_insertion_point(class_scope:io.prometheus.client.Untyped)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  double value_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_metrics_2eproto();
  friend void protobuf_AssignDesc_metrics_2eproto();
  friend void protobuf_ShutdownFile_metrics_2eproto();

  void InitAsDefaultInstance();
  static Untyped* default_instance_;
};
// -------------------------------------------------------------------

class Histogram : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:io.prometheus.client.Histogram) */ {
 public:
  Histogram();
  virtual ~Histogram();

  Histogram(const Histogram& from);

  inline Histogram& operator=(const Histogram& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Histogram& default_instance();

  void Swap(Histogram* other);

  // implements Message ----------------------------------------------

  inline Histogram* New() const { return New(NULL); }

  Histogram* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Histogram& from);
  void MergeFrom(const Histogram& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Histogram* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint64 sample_count = 1;
  void clear_sample_count();
  static const int kSampleCountFieldNumber = 1;
  ::google::protobuf::uint64 sample_count() const;
  void set_sample_count(::google::protobuf::uint64 value);

  // optional double sample_sum = 2;
  void clear_sample_sum();
  static const int kSampleSumFieldNumber = 2;
  double sample_sum() const;
  void set_sample_sum(double value);

  // repeated .io.prometheus.client.Bucket bucket = 3;
  int bucket_size() const;
  void clear_bucket();
  static const int kBucketFieldNumber = 3;
  const ::io::prometheus::client::Bucket& bucket(int index) const;
  ::io::prometheus::client::Bucket* mutable_bucket(int index);
  ::io::prometheus::client::Bucket* add_bucket();
  ::google::protobuf::RepeatedPtrField< ::io::prometheus::client::Bucket >*
      mutable_bucket();
  const ::google::protobuf::RepeatedPtrField< ::io::prometheus::client::Bucket >&
      bucket() const;

  // @@protoc_insertion_point(class_scope:io.prometheus.client.Histogram)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::uint64 sample_count_;
  double sample_sum_;
  ::google::protobuf::RepeatedPtrField< ::io::prometheus::client::Bucket > bucket_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_metrics_2eproto();
  friend void protobuf_AssignDesc_metrics_2eproto();
  friend void protobuf_ShutdownFile_metrics_2eproto();

  void InitAsDefaultInstance();
  static Histogram* default_instance_;
};
// -------------------------------------------------------------------

class Bucket : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:io.prometheus.client.Bucket) */ {
 public:
  Bucket();
  virtual ~Bucket();

  Bucket(const Bucket& from);

  inline Bucket& operator=(const Bucket& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Bucket& default_instance();

  void Swap(Bucket* other);

  // implements Message ----------------------------------------------

  inline Bucket* New() const { return New(NULL); }

  Bucket* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Bucket& from);
  void MergeFrom(const Bucket& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Bucket* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint64 cumulative_count = 1;
  void clear_cumulative_count();
  static const int kCumulativeCountFieldNumber = 1;
  ::google::protobuf::uint64 cumulative_count() const;
  void set_cumulative_count(::google::protobuf::uint64 value);

  // optional double upper_bound = 2;
  void clear_upper_bound();
  static const int kUpperBoundFieldNumber = 2;
  double upper_bound() const;
  void set_upper_bound(double value);

  // @@protoc_insertion_point(class_scope:io.prometheus.client.Bucket)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::uint64 cumulative_count_;
  double upper_bound_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_metrics_2eproto();
  friend void protobuf_AssignDesc_metrics_2eproto();
  friend void protobuf_ShutdownFile_metrics_2eproto();

  void InitAsDefaultInstance();
  static Bucket* default_instance_;
};
// -------------------------------------------------------------------

class Metric : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:io.prometheus.client.Metric) */ {
 public:
  Metric();
  virtual ~Metric();

  Metric(const Metric& from);

  inline Metric& operator=(const Metric& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Metric& default_instance();

  void Swap(Metric* other);

  // implements Message ----------------------------------------------

  inline Metric* New() const { return New(NULL); }

  Metric* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Metric& from);
  void MergeFrom(const Metric& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Metric* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .io.prometheus.client.LabelPair label = 1;
  int label_size() const;
  void clear_label();
  static const int kLabelFieldNumber = 1;
  const ::io::prometheus::client::LabelPair& label(int index) const;
  ::io::prometheus::client::LabelPair* mutable_label(int index);
  ::io::prometheus::client::LabelPair* add_label();
  ::google::protobuf::RepeatedPtrField< ::io::prometheus::client::LabelPair >*
      mutable_label();
  const ::google::protobuf::RepeatedPtrField< ::io::prometheus::client::LabelPair >&
      label() const;

  // optional .io.prometheus.client.Gauge gauge = 2;
  bool has_gauge() const;
  void clear_gauge();
  static const int kGaugeFieldNumber = 2;
  const ::io::prometheus::client::Gauge& gauge() const;
  ::io::prometheus::client::Gauge* mutable_gauge();
  ::io::prometheus::client::Gauge* release_gauge();
  void set_allocated_gauge(::io::prometheus::client::Gauge* gauge);

  // optional .io.prometheus.client.Counter counter = 3;
  bool has_counter() const;
  void clear_counter();
  static const int kCounterFieldNumber = 3;
  const ::io::prometheus::client::Counter& counter() const;
  ::io::prometheus::client::Counter* mutable_counter();
  ::io::prometheus::client::Counter* release_counter();
  void set_allocated_counter(::io::prometheus::client::Counter* counter);

  // optional .io.prometheus.client.Summary summary = 4;
  bool has_summary() const;
  void clear_summary();
  static const int kSummaryFieldNumber = 4;
  const ::io::prometheus::client::Summary& summary() const;
  ::io::prometheus::client::Summary* mutable_summary();
  ::io::prometheus::client::Summary* release_summary();
  void set_allocated_summary(::io::prometheus::client::Summary* summary);

  // optional .io.prometheus.client.Untyped untyped = 5;
  bool has_untyped() const;
  void clear_untyped();
  static const int kUntypedFieldNumber = 5;
  const ::io::prometheus::client::Untyped& untyped() const;
  ::io::prometheus::client::Untyped* mutable_untyped();
  ::io::prometheus::client::Untyped* release_untyped();
  void set_allocated_untyped(::io::prometheus::client::Untyped* untyped);

  // optional .io.prometheus.client.Histogram histogram = 7;
  bool has_histogram() const;
  void clear_histogram();
  static const int kHistogramFieldNumber = 7;
  const ::io::prometheus::client::Histogram& histogram() const;
  ::io::prometheus::client::Histogram* mutable_histogram();
  ::io::prometheus::client::Histogram* release_histogram();
  void set_allocated_histogram(::io::prometheus::client::Histogram* histogram);

  // optional int64 timestamp_ms = 6;
  void clear_timestamp_ms();
  static const int kTimestampMsFieldNumber = 6;
  ::google::protobuf::int64 timestamp_ms() const;
  void set_timestamp_ms(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:io.prometheus.client.Metric)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::RepeatedPtrField< ::io::prometheus::client::LabelPair > label_;
  ::io::prometheus::client::Gauge* gauge_;
  ::io::prometheus::client::Counter* counter_;
  ::io::prometheus::client::Summary* summary_;
  ::io::prometheus::client::Untyped* untyped_;
  ::io::prometheus::client::Histogram* histogram_;
  ::google::protobuf::int64 timestamp_ms_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_metrics_2eproto();
  friend void protobuf_AssignDesc_metrics_2eproto();
  friend void protobuf_ShutdownFile_metrics_2eproto();

  void InitAsDefaultInstance();
  static Metric* default_instance_;
};
// -------------------------------------------------------------------

class MetricFamily : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:io.prometheus.client.MetricFamily) */ {
 public:
  MetricFamily();
  virtual ~MetricFamily();

  MetricFamily(const MetricFamily& from);

  inline MetricFamily& operator=(const MetricFamily& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MetricFamily& default_instance();

  void Swap(MetricFamily* other);

  // implements Message ----------------------------------------------

  inline MetricFamily* New() const { return New(NULL); }

  MetricFamily* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MetricFamily& from);
  void MergeFrom(const MetricFamily& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(MetricFamily* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string name = 1;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // optional string help = 2;
  void clear_help();
  static const int kHelpFieldNumber = 2;
  const ::std::string& help() const;
  void set_help(const ::std::string& value);
  void set_help(const char* value);
  void set_help(const char* value, size_t size);
  ::std::string* mutable_help();
  ::std::string* release_help();
  void set_allocated_help(::std::string* help);

  // optional .io.prometheus.client.MetricType type = 3;
  void clear_type();
  static const int kTypeFieldNumber = 3;
  ::io::prometheus::client::MetricType type() const;
  void set_type(::io::prometheus::client::MetricType value);

  // repeated .io.prometheus.client.Metric metric = 4;
  int metric_size() const;
  void clear_metric();
  static const int kMetricFieldNumber = 4;
  const ::io::prometheus::client::Metric& metric(int index) const;
  ::io::prometheus::client::Metric* mutable_metric(int index);
  ::io::prometheus::client::Metric* add_metric();
  ::google::protobuf::RepeatedPtrField< ::io::prometheus::client::Metric >*
      mutable_metric();
  const ::google::protobuf::RepeatedPtrField< ::io::prometheus::client::Metric >&
      metric() const;

  // @@protoc_insertion_point(class_scope:io.prometheus.client.MetricFamily)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::internal::ArenaStringPtr help_;
  ::google::protobuf::RepeatedPtrField< ::io::prometheus::client::Metric > metric_;
  int type_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_metrics_2eproto();
  friend void protobuf_AssignDesc_metrics_2eproto();
  friend void protobuf_ShutdownFile_metrics_2eproto();

  void InitAsDefaultInstance();
  static MetricFamily* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// LabelPair

// optional string name = 1;
inline void LabelPair::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& LabelPair::name() const {
  // @@protoc_insertion_point(field_get:io.prometheus.client.LabelPair.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LabelPair::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:io.prometheus.client.LabelPair.name)
}
inline void LabelPair::set_name(const char* value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:io.prometheus.client.LabelPair.name)
}
inline void LabelPair::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:io.prometheus.client.LabelPair.name)
}
inline ::std::string* LabelPair::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:io.prometheus.client.LabelPair.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* LabelPair::release_name() {
  // @@protoc_insertion_point(field_release:io.prometheus.client.LabelPair.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LabelPair::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:io.prometheus.client.LabelPair.name)
}

// optional string value = 2;
inline void LabelPair::clear_value() {
  value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& LabelPair::value() const {
  // @@protoc_insertion_point(field_get:io.prometheus.client.LabelPair.value)
  return value_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LabelPair::set_value(const ::std::string& value) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:io.prometheus.client.LabelPair.value)
}
inline void LabelPair::set_value(const char* value) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:io.prometheus.client.LabelPair.value)
}
inline void LabelPair::set_value(const char* value, size_t size) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:io.prometheus.client.LabelPair.value)
}
inline ::std::string* LabelPair::mutable_value() {
  
  // @@protoc_insertion_point(field_mutable:io.prometheus.client.LabelPair.value)
  return value_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* LabelPair::release_value() {
  // @@protoc_insertion_point(field_release:io.prometheus.client.LabelPair.value)
  
  return value_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LabelPair::set_allocated_value(::std::string* value) {
  if (value != NULL) {
    
  } else {
    
  }
  value_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set_allocated:io.prometheus.client.LabelPair.value)
}

// -------------------------------------------------------------------

// Gauge

// optional double value = 1;
inline void Gauge::clear_value() {
  value_ = 0;
}
inline double Gauge::value() const {
  // @@protoc_insertion_point(field_get:io.prometheus.client.Gauge.value)
  return value_;
}
inline void Gauge::set_value(double value) {
  
  value_ = value;
  // @@protoc_insertion_point(field_set:io.prometheus.client.Gauge.value)
}

// -------------------------------------------------------------------

// Counter

// optional double value = 1;
inline void Counter::clear_value() {
  value_ = 0;
}
inline double Counter::value() const {
  // @@protoc_insertion_point(field_get:io.prometheus.client.Counter.value)
  return value_;
}
inline void Counter::set_value(double value) {
  
  value_ = value;
  // @@protoc_insertion_point(field_set:io.prometheus.client.Counter.value)
}

// -------------------------------------------------------------------

// Quantile

// optional double quantile = 1;
inline void Quantile::clear_quantile() {
  quantile_ = 0;
}
inline double Quantile::quantile() const {
  // @@protoc_insertion_point(field_get:io.prometheus.client.Quantile.quantile)
  return quantile_;
}
inline void Quantile::set_quantile(double value) {
  
  quantile_ = value;
  // @@protoc_insertion_point(field_set:io.prometheus.client.Quantile.quantile)
}

// optional double value = 2;
inline void Quantile::clear_value() {
  value_ = 0;
}
inline double Quantile::value() const {
  // @@protoc_insertion_point(field_get:io.prometheus.client.Quantile.value)
  return value_;
}
inline void Quantile::set_value(double value) {
  
  value_ = value;
  // @@protoc_insertion_point(field_set:io.prometheus.client.Quantile.value)
}

// -------------------------------------------------------------------

// Summary

// optional uint64 sample_count = 1;
inline void Summary::clear_sample_count() {
  sample_count_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Summary::sample_count() const {
  // @@protoc_insertion_point(field_get:io.prometheus.client.Summary.sample_count)
  return sample_count_;
}
inline void Summary::set_sample_count(::google::protobuf::uint64 value) {
  
  sample_count_ = value;
  // @@protoc_insertion_point(field_set:io.prometheus.client.Summary.sample_count)
}

// optional double sample_sum = 2;
inline void Summary::clear_sample_sum() {
  sample_sum_ = 0;
}
inline double Summary::sample_sum() const {
  // @@protoc_insertion_point(field_get:io.prometheus.client.Summary.sample_sum)
  return sample_sum_;
}
inline void Summary::set_sample_sum(double value) {
  
  sample_sum_ = value;
  // @@protoc_insertion_point(field_set:io.prometheus.client.Summary.sample_sum)
}

// repeated .io.prometheus.client.Quantile quantile = 3;
inline int Summary::quantile_size() const {
  return quantile_.size();
}
inline void Summary::clear_quantile() {
  quantile_.Clear();
}
inline const ::io::prometheus::client::Quantile& Summary::quantile(int index) const {
  // @@protoc_insertion_point(field_get:io.prometheus.client.Summary.quantile)
  return quantile_.Get(index);
}
inline ::io::prometheus::client::Quantile* Summary::mutable_quantile(int index) {
  // @@protoc_insertion_point(field_mutable:io.prometheus.client.Summary.quantile)
  return quantile_.Mutable(index);
}
inline ::io::prometheus::client::Quantile* Summary::add_quantile() {
  // @@protoc_insertion_point(field_add:io.prometheus.client.Summary.quantile)
  return quantile_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::io::prometheus::client::Quantile >*
Summary::mutable_quantile() {
  // @@protoc_insertion_point(field_mutable_list:io.prometheus.client.Summary.quantile)
  return &quantile_;
}
inline const ::google::protobuf::RepeatedPtrField< ::io::prometheus::client::Quantile >&
Summary::quantile() const {
  // @@protoc_insertion_point(field_list:io.prometheus.client.Summary.quantile)
  return quantile_;
}

// -------------------------------------------------------------------

// Untyped

// optional double value = 1;
inline void Untyped::clear_value() {
  value_ = 0;
}
inline double Untyped::value() const {
  // @@protoc_insertion_point(field_get:io.prometheus.client.Untyped.value)
  return value_;
}
inline void Untyped::set_value(double value) {
  
  value_ = value;
  // @@protoc_insertion_point(field_set:io.prometheus.client.Untyped.value)
}

// -------------------------------------------------------------------

// Histogram

// optional uint64 sample_count = 1;
inline void Histogram::clear_sample_count() {
  sample_count_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Histogram::sample_count() const {
  // @@protoc_insertion_point(field_get:io.prometheus.client.Histogram.sample_count)
  return sample_count_;
}
inline void Histogram::set_sample_count(::google::protobuf::uint64 value) {
  
  sample_count_ = value;
  // @@protoc_insertion_point(field_set:io.prometheus.client.Histogram.sample_count)
}

// optional double sample_sum = 2;
inline void Histogram::clear_sample_sum() {
  sample_sum_ = 0;
}
inline double Histogram::sample_sum() const {
  // @@protoc_insertion_point(field_get:io.prometheus.client.Histogram.sample_sum)
  return sample_sum_;
}
inline void Histogram::set_sample_sum(double value) {
  
  sample_sum_ = value;
  // @@protoc_insertion_point(field_set:io.prometheus.client.Histogram.sample_sum)
}

// repeated .io.prometheus.client.Bucket bucket = 3;
inline int Histogram::bucket_size() const {
  return bucket_.size();
}
inline void Histogram::clear_bucket() {
  bucket_.Clear();
}
inline const ::io::prometheus::client::Bucket& Histogram::bucket(int index) const {
  // @@protoc_insertion_point(field_get:io.prometheus.client.Histogram.bucket)
  return bucket_.Get(index);
}
inline ::io::prometheus::client::Bucket* Histogram::mutable_bucket(int index) {
  // @@protoc_insertion_point(field_mutable:io.prometheus.client.Histogram.bucket)
  return bucket_.Mutable(index);
}
inline ::io::prometheus::client::Bucket* Histogram::add_bucket() {
  // @@protoc_insertion_point(field_add:io.prometheus.client.Histogram.bucket)
  return bucket_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::io::prometheus::client::Bucket >*
Histogram::mutable_bucket() {
  // @@protoc_insertion_point(field_mutable_list:io.prometheus.client.Histogram.bucket)
  return &bucket_;
}
inline const ::google::protobuf::RepeatedPtrField< ::io::prometheus::client::Bucket >&
Histogram::bucket() const {
  // @@protoc_insertion_point(field_list:io.prometheus.client.Histogram.bucket)
  return bucket_;
}

// -------------------------------------------------------------------

// Bucket

// optional uint64 cumulative_count = 1;
inline void Bucket::clear_cumulative_count() {
  cumulative_count_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Bucket::cumulative_count() const {
  // @@protoc_insertion_point(field_get:io.prometheus.client.Bucket.cumulative_count)
  return cumulative_count_;
}
inline void Bucket::set_cumulative_count(::google::protobuf::uint64 value) {
  
  cumulative_count_ = value;
  // @@protoc_insertion_point(field_set:io.prometheus.client.Bucket.cumulative_count)
}

// optional double upper_bound = 2;
inline void Bucket::clear_upper_bound() {
  upper_bound_ = 0;
}
inline double Bucket::upper_bound() const {
  // @@protoc_insertion_point(field_get:io.prometheus.client.Bucket.upper_bound)
  return upper_bound_;
}
inline void Bucket::set_upper_bound(double value) {
  
  upper_bound_ = value;
  // @@protoc_insertion_point(field_set:io.prometheus.client.Bucket.upper_bound)
}

// -------------------------------------------------------------------

// Metric

// repeated .io.prometheus.client.LabelPair label = 1;
inline int Metric::label_size() const {
  return label_.size();
}
inline void Metric::clear_label() {
  label_.Clear();
}
inline const ::io::prometheus::client::LabelPair& Metric::label(int index) const {
  // @@protoc_insertion_point(field_get:io.prometheus.client.Metric.label)
  return label_.Get(index);
}
inline ::io::prometheus::client::LabelPair* Metric::mutable_label(int index) {
  // @@protoc_insertion_point(field_mutable:io.prometheus.client.Metric.label)
  return label_.Mutable(index);
}
inline ::io::prometheus::client::LabelPair* Metric::add_label() {
  // @@protoc_insertion_point(field_add:io.prometheus.client.Metric.label)
  return label_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::io::prometheus::client::LabelPair >*
Metric::mutable_label() {
  // @@protoc_insertion_point(field_mutable_list:io.prometheus.client.Metric.label)
  return &label_;
}
inline const ::google::protobuf::RepeatedPtrField< ::io::prometheus::client::LabelPair >&
Metric::label() const {
  // @@protoc_insertion_point(field_list:io.prometheus.client.Metric.label)
  return label_;
}

// optional .io.prometheus.client.Gauge gauge = 2;
inline bool Metric::has_gauge() const {
  return !_is_default_instance_ && gauge_ != NULL;
}
inline void Metric::clear_gauge() {
  if (GetArenaNoVirtual() == NULL && gauge_ != NULL) delete gauge_;
  gauge_ = NULL;
}
inline const ::io::prometheus::client::Gauge& Metric::gauge() const {
  // @@protoc_insertion_point(field_get:io.prometheus.client.Metric.gauge)
  return gauge_ != NULL ? *gauge_ : *default_instance_->gauge_;
}
inline ::io::prometheus::client::Gauge* Metric::mutable_gauge() {
  
  if (gauge_ == NULL) {
    gauge_ = new ::io::prometheus::client::Gauge;
  }
  // @@protoc_insertion_point(field_mutable:io.prometheus.client.Metric.gauge)
  return gauge_;
}
inline ::io::prometheus::client::Gauge* Metric::release_gauge() {
  // @@protoc_insertion_point(field_release:io.prometheus.client.Metric.gauge)
  
  ::io::prometheus::client::Gauge* temp = gauge_;
  gauge_ = NULL;
  return temp;
}
inline void Metric::set_allocated_gauge(::io::prometheus::client::Gauge* gauge) {
  delete gauge_;
  gauge_ = gauge;
  if (gauge) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:io.prometheus.client.Metric.gauge)
}

// optional .io.prometheus.client.Counter counter = 3;
inline bool Metric::has_counter() const {
  return !_is_default_instance_ && counter_ != NULL;
}
inline void Metric::clear_counter() {
  if (GetArenaNoVirtual() == NULL && counter_ != NULL) delete counter_;
  counter_ = NULL;
}
inline const ::io::prometheus::client::Counter& Metric::counter() const {
  // @@protoc_insertion_point(field_get:io.prometheus.client.Metric.counter)
  return counter_ != NULL ? *counter_ : *default_instance_->counter_;
}
inline ::io::prometheus::client::Counter* Metric::mutable_counter() {
  
  if (counter_ == NULL) {
    counter_ = new ::io::prometheus::client::Counter;
  }
  // @@protoc_insertion_point(field_mutable:io.prometheus.client.Metric.counter)
  return counter_;
}
inline ::io::prometheus::client::Counter* Metric::release_counter() {
  // @@protoc_insertion_point(field_release:io.prometheus.client.Metric.counter)
  
  ::io::prometheus::client::Counter* temp = counter_;
  counter_ = NULL;
  return temp;
}
inline void Metric::set_allocated_counter(::io::prometheus::client::Counter* counter) {
  delete counter_;
  counter_ = counter;
  if (counter) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:io.prometheus.client.Metric.counter)
}

// optional .io.prometheus.client.Summary summary = 4;
inline bool Metric::has_summary() const {
  return !_is_default_instance_ && summary_ != NULL;
}
inline void Metric::clear_summary() {
  if (GetArenaNoVirtual() == NULL && summary_ != NULL) delete summary_;
  summary_ = NULL;
}
inline const ::io::prometheus::client::Summary& Metric::summary() const {
  // @@protoc_insertion_point(field_get:io.prometheus.client.Metric.summary)
  return summary_ != NULL ? *summary_ : *default_instance_->summary_;
}
inline ::io::prometheus::client::Summary* Metric::mutable_summary() {
  
  if (summary_ == NULL) {
    summary_ = new ::io::prometheus::client::Summary;
  }
  // @@protoc_insertion_point(field_mutable:io.prometheus.client.Metric.summary)
  return summary_;
}
inline ::io::prometheus::client::Summary* Metric::release_summary() {
  // @@protoc_insertion_point(field_release:io.prometheus.client.Metric.summary)
  
  ::io::prometheus::client::Summary* temp = summary_;
  summary_ = NULL;
  return temp;
}
inline void Metric::set_allocated_summary(::io::prometheus::client::Summary* summary) {
  delete summary_;
  summary_ = summary;
  if (summary) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:io.prometheus.client.Metric.summary)
}

// optional .io.prometheus.client.Untyped untyped = 5;
inline bool Metric::has_untyped() const {
  return !_is_default_instance_ && untyped_ != NULL;
}
inline void Metric::clear_untyped() {
  if (GetArenaNoVirtual() == NULL && untyped_ != NULL) delete untyped_;
  untyped_ = NULL;
}
inline const ::io::prometheus::client::Untyped& Metric::untyped() const {
  // @@protoc_insertion_point(field_get:io.prometheus.client.Metric.untyped)
  return untyped_ != NULL ? *untyped_ : *default_instance_->untyped_;
}
inline ::io::prometheus::client::Untyped* Metric::mutable_untyped() {
  
  if (untyped_ == NULL) {
    untyped_ = new ::io::prometheus::client::Untyped;
  }
  // @@protoc_insertion_point(field_mutable:io.prometheus.client.Metric.untyped)
  return untyped_;
}
inline ::io::prometheus::client::Untyped* Metric::release_untyped() {
  // @@protoc_insertion_point(field_release:io.prometheus.client.Metric.untyped)
  
  ::io::prometheus::client::Untyped* temp = untyped_;
  untyped_ = NULL;
  return temp;
}
inline void Metric::set_allocated_untyped(::io::prometheus::client::Untyped* untyped) {
  delete untyped_;
  untyped_ = untyped;
  if (untyped) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:io.prometheus.client.Metric.untyped)
}

// optional .io.prometheus.client.Histogram histogram = 7;
inline bool Metric::has_histogram() const {
  return !_is_default_instance_ && histogram_ != NULL;
}
inline void Metric::clear_histogram() {
  if (GetArenaNoVirtual() == NULL && histogram_ != NULL) delete histogram_;
  histogram_ = NULL;
}
inline const ::io::prometheus::client::Histogram& Metric::histogram() const {
  // @@protoc_insertion_point(field_get:io.prometheus.client.Metric.histogram)
  return histogram_ != NULL ? *histogram_ : *default_instance_->histogram_;
}
inline ::io::prometheus::client::Histogram* Metric::mutable_histogram() {
  
  if (histogram_ == NULL) {
    histogram_ = new ::io::prometheus::client::Histogram;
  }
  // @@protoc_insertion_point(field_mutable:io.prometheus.client.Metric.histogram)
  return histogram_;
}
inline ::io::prometheus::client::Histogram* Metric::release_histogram() {
  // @@protoc_insertion_point(field_release:io.prometheus.client.Metric.histogram)
  
  ::io::prometheus::client::Histogram* temp = histogram_;
  histogram_ = NULL;
  return temp;
}
inline void Metric::set_allocated_histogram(::io::prometheus::client::Histogram* histogram) {
  delete histogram_;
  histogram_ = histogram;
  if (histogram) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:io.prometheus.client.Metric.histogram)
}

// optional int64 timestamp_ms = 6;
inline void Metric::clear_timestamp_ms() {
  timestamp_ms_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 Metric::timestamp_ms() const {
  // @@protoc_insertion_point(field_get:io.prometheus.client.Metric.timestamp_ms)
  return timestamp_ms_;
}
inline void Metric::set_timestamp_ms(::google::protobuf::int64 value) {
  
  timestamp_ms_ = value;
  // @@protoc_insertion_point(field_set:io.prometheus.client.Metric.timestamp_ms)
}

// -------------------------------------------------------------------

// MetricFamily

// optional string name = 1;
inline void MetricFamily::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& MetricFamily::name() const {
  // @@protoc_insertion_point(field_get:io.prometheus.client.MetricFamily.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MetricFamily::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:io.prometheus.client.MetricFamily.name)
}
inline void MetricFamily::set_name(const char* value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:io.prometheus.client.MetricFamily.name)
}
inline void MetricFamily::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:io.prometheus.client.MetricFamily.name)
}
inline ::std::string* MetricFamily::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:io.prometheus.client.MetricFamily.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* MetricFamily::release_name() {
  // @@protoc_insertion_point(field_release:io.prometheus.client.MetricFamily.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MetricFamily::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:io.prometheus.client.MetricFamily.name)
}

// optional string help = 2;
inline void MetricFamily::clear_help() {
  help_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& MetricFamily::help() const {
  // @@protoc_insertion_point(field_get:io.prometheus.client.MetricFamily.help)
  return help_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MetricFamily::set_help(const ::std::string& value) {
  
  help_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:io.prometheus.client.MetricFamily.help)
}
inline void MetricFamily::set_help(const char* value) {
  
  help_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:io.prometheus.client.MetricFamily.help)
}
inline void MetricFamily::set_help(const char* value, size_t size) {
  
  help_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:io.prometheus.client.MetricFamily.help)
}
inline ::std::string* MetricFamily::mutable_help() {
  
  // @@protoc_insertion_point(field_mutable:io.prometheus.client.MetricFamily.help)
  return help_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* MetricFamily::release_help() {
  // @@protoc_insertion_point(field_release:io.prometheus.client.MetricFamily.help)
  
  return help_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MetricFamily::set_allocated_help(::std::string* help) {
  if (help != NULL) {
    
  } else {
    
  }
  help_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), help);
  // @@protoc_insertion_point(field_set_allocated:io.prometheus.client.MetricFamily.help)
}

// optional .io.prometheus.client.MetricType type = 3;
inline void MetricFamily::clear_type() {
  type_ = 0;
}
inline ::io::prometheus::client::MetricType MetricFamily::type() const {
  // @@protoc_insertion_point(field_get:io.prometheus.client.MetricFamily.type)
  return static_cast< ::io::prometheus::client::MetricType >(type_);
}
inline void MetricFamily::set_type(::io::prometheus::client::MetricType value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:io.prometheus.client.MetricFamily.type)
}

// repeated .io.prometheus.client.Metric metric = 4;
inline int MetricFamily::metric_size() const {
  return metric_.size();
}
inline void MetricFamily::clear_metric() {
  metric_.Clear();
}
inline const ::io::prometheus::client::Metric& MetricFamily::metric(int index) const {
  // @@protoc_insertion_point(field_get:io.prometheus.client.MetricFamily.metric)
  return metric_.Get(index);
}
inline ::io::prometheus::client::Metric* MetricFamily::mutable_metric(int index) {
  // @@protoc_insertion_point(field_mutable:io.prometheus.client.MetricFamily.metric)
  return metric_.Mutable(index);
}
inline ::io::prometheus::client::Metric* MetricFamily::add_metric() {
  // @@protoc_insertion_point(field_add:io.prometheus.client.MetricFamily.metric)
  return metric_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::io::prometheus::client::Metric >*
MetricFamily::mutable_metric() {
  // @@protoc_insertion_point(field_mutable_list:io.prometheus.client.MetricFamily.metric)
  return &metric_;
}
inline const ::google::protobuf::RepeatedPtrField< ::io::prometheus::client::Metric >&
MetricFamily::metric() const {
  // @@protoc_insertion_point(field_list:io.prometheus.client.MetricFamily.metric)
  return metric_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace client
}  // namespace prometheus
}  // namespace io

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::io::prometheus::client::MetricType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::io::prometheus::client::MetricType>() {
  return ::io::prometheus::client::MetricType_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_metrics_2eproto__INCLUDED
