// Code generated by protoc-gen-go. DO NOT EDIT.
// source: io/prometheus/client/metrics.proto

package io_prometheus_client

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MetricType int32

const (
	// COUNTER must use the Metric field "counter".
	MetricType_COUNTER MetricType = 0
	// GAUGE must use the Metric field "gauge".
	MetricType_GAUGE MetricType = 1
	// SUMMARY must use the Metric field "summary".
	MetricType_SUMMARY MetricType = 2
	// UNTYPED must use the Metric field "untyped".
	MetricType_UNTYPED MetricType = 3
	// HISTOGRAM must use the Metric field "histogram".
	MetricType_HISTOGRAM MetricType = 4
	// GAUGE_HISTOGRAM must use the Metric field "histogram".
	MetricType_GAUGE_HISTOGRAM MetricType = 5
)

var MetricType_name = map[int32]string{
	0: "COUNTER",
	1: "GAUGE",
	2: "SUMMARY",
	3: "UNTYPED",
	4: "HISTOGRAM",
	5: "GAUGE_HISTOGRAM",
}

var MetricType_value = map[string]int32{
	"COUNTER":         0,
	"GAUGE":           1,
	"SUMMARY":         2,
	"UNTYPED":         3,
	"HISTOGRAM":       4,
	"GAUGE_HISTOGRAM": 5,
}

func (x MetricType) Enum() *MetricType {
	p := new(MetricType)
	*p = x
	return p
}

func (x MetricType) String() string {
	return proto.EnumName(MetricType_name, int32(x))
}

func (x *MetricType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MetricType_value, data, "MetricType")
	if err != nil {
		return err
	}
	*x = MetricType(value)
	return nil
}

func (MetricType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d1e5ddb18987a258, []int{0}
}

type LabelPair struct {
	Name                 *string  `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Value                *string  `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LabelPair) Reset()         { *m = LabelPair{} }
func (m *LabelPair) String() string { return proto.CompactTextString(m) }
func (*LabelPair) ProtoMessage()    {}
func (*LabelPair) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1e5ddb18987a258, []int{0}
}

func (m *LabelPair) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LabelPair.Unmarshal(m, b)
}
func (m *LabelPair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LabelPair.Marshal(b, m, deterministic)
}
func (m *LabelPair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LabelPair.Merge(m, src)
}
func (m *LabelPair) XXX_Size() int {
	return xxx_messageInfo_LabelPair.Size(m)
}
func (m *LabelPair) XXX_DiscardUnknown() {
	xxx_messageInfo_LabelPair.DiscardUnknown(m)
}

var xxx_messageInfo_LabelPair proto.InternalMessageInfo

func (m *LabelPair) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *LabelPair) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

type Gauge struct {
	Value                *float64 `protobuf:"fixed64,1,opt,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Gauge) Reset()         { *m = Gauge{} }
func (m *Gauge) String() string { return proto.CompactTextString(m) }
func (*Gauge) ProtoMessage()    {}
func (*Gauge) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1e5ddb18987a258, []int{1}
}

func (m *Gauge) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Gauge.Unmarshal(m, b)
}
func (m *Gauge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Gauge.Marshal(b, m, deterministic)
}
func (m *Gauge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Gauge.Merge(m, src)
}
func (m *Gauge) XXX_Size() int {
	return xxx_messageInfo_Gauge.Size(m)
}
func (m *Gauge) XXX_DiscardUnknown() {
	xxx_messageInfo_Gauge.DiscardUnknown(m)
}

var xxx_messageInfo_Gauge proto.InternalMessageInfo

func (m *Gauge) GetValue() float64 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

type Counter struct {
	Value                *float64  `protobuf:"fixed64,1,opt,name=value" json:"value,omitempty"`
	Exemplar             *Exemplar `protobuf:"bytes,2,opt,name=exemplar" json:"exemplar,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Counter) Reset()         { *m = Counter{} }
func (m *Counter) String() string { return proto.CompactTextString(m) }
func (*Counter) ProtoMessage()    {}
func (*Counter) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1e5ddb18987a258, []int{2}
}

func (m *Counter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Counter.Unmarshal(m, b)
}
func (m *Counter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Counter.Marshal(b, m, deterministic)
}
func (m *Counter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Counter.Merge(m, src)
}
func (m *Counter) XXX_Size() int {
	return xxx_messageInfo_Counter.Size(m)
}
func (m *Counter) XXX_DiscardUnknown() {
	xxx_messageInfo_Counter.DiscardUnknown(m)
}

var xxx_messageInfo_Counter proto.InternalMessageInfo

func (m *Counter) GetValue() float64 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

func (m *Counter) GetExemplar() *Exemplar {
	if m != nil {
		return m.Exemplar
	}
	return nil
}

type Quantile struct {
	Quantile             *float64 `protobuf:"fixed64,1,opt,name=quantile" json:"quantile,omitempty"`
	Value                *float64 `protobuf:"fixed64,2,opt,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Quantile) Reset()         { *m = Quantile{} }
func (m *Quantile) String() string { return proto.CompactTextString(m) }
func (*Quantile) ProtoMessage()    {}
func (*Quantile) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1e5ddb18987a258, []int{3}
}

func (m *Quantile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Quantile.Unmarshal(m, b)
}
func (m *Quantile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Quantile.Marshal(b, m, deterministic)
}
func (m *Quantile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Quantile.Merge(m, src)
}
func (m *Quantile) XXX_Size() int {
	return xxx_messageInfo_Quantile.Size(m)
}
func (m *Quantile) XXX_DiscardUnknown() {
	xxx_messageInfo_Quantile.DiscardUnknown(m)
}

var xxx_messageInfo_Quantile proto.InternalMessageInfo

func (m *Quantile) GetQuantile() float64 {
	if m != nil && m.Quantile != nil {
		return *m.Quantile
	}
	return 0
}

func (m *Quantile) GetValue() float64 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

type Summary struct {
	SampleCount          *uint64     `protobuf:"varint,1,opt,name=sample_count,json=sampleCount" json:"sample_count,omitempty"`
	SampleSum            *float64    `protobuf:"fixed64,2,opt,name=sample_sum,json=sampleSum" json:"sample_sum,omitempty"`
	Quantile             []*Quantile `protobuf:"bytes,3,rep,name=quantile" json:"quantile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Summary) Reset()         { *m = Summary{} }
func (m *Summary) String() string { return proto.CompactTextString(m) }
func (*Summary) ProtoMessage()    {}
func (*Summary) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1e5ddb18987a258, []int{4}
}

func (m *Summary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Summary.Unmarshal(m, b)
}
func (m *Summary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Summary.Marshal(b, m, deterministic)
}
func (m *Summary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Summary.Merge(m, src)
}
func (m *Summary) XXX_Size() int {
	return xxx_messageInfo_Summary.Size(m)
}
func (m *Summary) XXX_DiscardUnknown() {
	xxx_messageInfo_Summary.DiscardUnknown(m)
}

var xxx_messageInfo_Summary proto.InternalMessageInfo

func (m *Summary) GetSampleCount() uint64 {
	if m != nil && m.SampleCount != nil {
		return *m.SampleCount
	}
	return 0
}

func (m *Summary) GetSampleSum() float64 {
	if m != nil && m.SampleSum != nil {
		return *m.SampleSum
	}
	return 0
}

func (m *Summary) GetQuantile() []*Quantile {
	if m != nil {
		return m.Quantile
	}
	return nil
}

type Untyped struct {
	Value                *float64 `protobuf:"fixed64,1,opt,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Untyped) Reset()         { *m = Untyped{} }
func (m *Untyped) String() string { return proto.CompactTextString(m) }
func (*Untyped) ProtoMessage()    {}
func (*Untyped) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1e5ddb18987a258, []int{5}
}

func (m *Untyped) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Untyped.Unmarshal(m, b)
}
func (m *Untyped) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Untyped.Marshal(b, m, deterministic)
}
func (m *Untyped) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Untyped.Merge(m, src)
}
func (m *Untyped) XXX_Size() int {
	return xxx_messageInfo_Untyped.Size(m)
}
func (m *Untyped) XXX_DiscardUnknown() {
	xxx_messageInfo_Untyped.DiscardUnknown(m)
}

var xxx_messageInfo_Untyped proto.InternalMessageInfo

func (m *Untyped) GetValue() float64 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

type Histogram struct {
	SampleCount      *uint64   `protobuf:"varint,1,opt,name=sample_count,json=sampleCount" json:"sample_count,omitempty"`
	SampleCountFloat *float64  `protobuf:"fixed64,9,opt,name=sample_count_float,json=sampleCountFloat" json:"sample_count_float,omitempty"`
	SampleSum        *float64  `protobuf:"fixed64,2,opt,name=sample_sum,json=sampleSum" json:"sample_sum,omitempty"`
	Bucket           []*Bucket `protobuf:"bytes,3,rep,name=bucket" json:"bucket,omitempty"`
	// Sparse bucket (sb) stuff:
	// The sb_schema defines the bucket schema. Currently, valid numbers are -4 <= n <= 8.
	// They are all for base-2 bucket schemas, where 1 is a bucket boundary in each case, and
	// then each power of two is divided into 2^n logarithmic buckets.
	// Or in other words, each bucket boundary is the previous boundary times 2^(2^-n).
	// In the future, more bucket schemas may be added using numbers < -4 or > 8.
	SbSchema             *int32         `protobuf:"zigzag32,4,opt,name=sb_schema,json=sbSchema" json:"sb_schema,omitempty"`
	SbZeroThreshold      *float64       `protobuf:"fixed64,5,opt,name=sb_zero_threshold,json=sbZeroThreshold" json:"sb_zero_threshold,omitempty"`
	SbZeroCount          *uint64        `protobuf:"varint,6,opt,name=sb_zero_count,json=sbZeroCount" json:"sb_zero_count,omitempty"`
	SbZeroCountFloat     *float64       `protobuf:"fixed64,10,opt,name=sb_zero_count_float,json=sbZeroCountFloat" json:"sb_zero_count_float,omitempty"`
	SbNegative           *SparseBuckets `protobuf:"bytes,7,opt,name=sb_negative,json=sbNegative" json:"sb_negative,omitempty"`
	SbPositive           *SparseBuckets `protobuf:"bytes,8,opt,name=sb_positive,json=sbPositive" json:"sb_positive,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Histogram) Reset()         { *m = Histogram{} }
func (m *Histogram) String() string { return proto.CompactTextString(m) }
func (*Histogram) ProtoMessage()    {}
func (*Histogram) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1e5ddb18987a258, []int{6}
}

func (m *Histogram) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Histogram.Unmarshal(m, b)
}
func (m *Histogram) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Histogram.Marshal(b, m, deterministic)
}
func (m *Histogram) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Histogram.Merge(m, src)
}
func (m *Histogram) XXX_Size() int {
	return xxx_messageInfo_Histogram.Size(m)
}
func (m *Histogram) XXX_DiscardUnknown() {
	xxx_messageInfo_Histogram.DiscardUnknown(m)
}

var xxx_messageInfo_Histogram proto.InternalMessageInfo

func (m *Histogram) GetSampleCount() uint64 {
	if m != nil && m.SampleCount != nil {
		return *m.SampleCount
	}
	return 0
}

func (m *Histogram) GetSampleCountFloat() float64 {
	if m != nil && m.SampleCountFloat != nil {
		return *m.SampleCountFloat
	}
	return 0
}

func (m *Histogram) GetSampleSum() float64 {
	if m != nil && m.SampleSum != nil {
		return *m.SampleSum
	}
	return 0
}

func (m *Histogram) GetBucket() []*Bucket {
	if m != nil {
		return m.Bucket
	}
	return nil
}

func (m *Histogram) GetSbSchema() int32 {
	if m != nil && m.SbSchema != nil {
		return *m.SbSchema
	}
	return 0
}

func (m *Histogram) GetSbZeroThreshold() float64 {
	if m != nil && m.SbZeroThreshold != nil {
		return *m.SbZeroThreshold
	}
	return 0
}

func (m *Histogram) GetSbZeroCount() uint64 {
	if m != nil && m.SbZeroCount != nil {
		return *m.SbZeroCount
	}
	return 0
}

func (m *Histogram) GetSbZeroCountFloat() float64 {
	if m != nil && m.SbZeroCountFloat != nil {
		return *m.SbZeroCountFloat
	}
	return 0
}

func (m *Histogram) GetSbNegative() *SparseBuckets {
	if m != nil {
		return m.SbNegative
	}
	return nil
}

func (m *Histogram) GetSbPositive() *SparseBuckets {
	if m != nil {
		return m.SbPositive
	}
	return nil
}

type Bucket struct {
	CumulativeCount      *uint64   `protobuf:"varint,1,opt,name=cumulative_count,json=cumulativeCount" json:"cumulative_count,omitempty"`
	CumulativeCountFloat *float64  `protobuf:"fixed64,4,opt,name=cumulative_count_float,json=cumulativeCountFloat" json:"cumulative_count_float,omitempty"`
	UpperBound           *float64  `protobuf:"fixed64,2,opt,name=upper_bound,json=upperBound" json:"upper_bound,omitempty"`
	Exemplar             *Exemplar `protobuf:"bytes,3,opt,name=exemplar" json:"exemplar,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Bucket) Reset()         { *m = Bucket{} }
func (m *Bucket) String() string { return proto.CompactTextString(m) }
func (*Bucket) ProtoMessage()    {}
func (*Bucket) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1e5ddb18987a258, []int{7}
}

func (m *Bucket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bucket.Unmarshal(m, b)
}
func (m *Bucket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bucket.Marshal(b, m, deterministic)
}
func (m *Bucket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bucket.Merge(m, src)
}
func (m *Bucket) XXX_Size() int {
	return xxx_messageInfo_Bucket.Size(m)
}
func (m *Bucket) XXX_DiscardUnknown() {
	xxx_messageInfo_Bucket.DiscardUnknown(m)
}

var xxx_messageInfo_Bucket proto.InternalMessageInfo

func (m *Bucket) GetCumulativeCount() uint64 {
	if m != nil && m.CumulativeCount != nil {
		return *m.CumulativeCount
	}
	return 0
}

func (m *Bucket) GetCumulativeCountFloat() float64 {
	if m != nil && m.CumulativeCountFloat != nil {
		return *m.CumulativeCountFloat
	}
	return 0
}

func (m *Bucket) GetUpperBound() float64 {
	if m != nil && m.UpperBound != nil {
		return *m.UpperBound
	}
	return 0
}

func (m *Bucket) GetExemplar() *Exemplar {
	if m != nil {
		return m.Exemplar
	}
	return nil
}

type SparseBuckets struct {
	Span []*SparseBuckets_Span `protobuf:"bytes,1,rep,name=span" json:"span,omitempty"`
	// Only one of "delta" or "count" may be used, the former for regular
	// histograms with integer counts, the latter for float histograms.
	Delta                []int64   `protobuf:"zigzag64,2,rep,name=delta" json:"delta,omitempty"`
	Count                []float64 `protobuf:"fixed64,3,rep,name=count" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SparseBuckets) Reset()         { *m = SparseBuckets{} }
func (m *SparseBuckets) String() string { return proto.CompactTextString(m) }
func (*SparseBuckets) ProtoMessage()    {}
func (*SparseBuckets) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1e5ddb18987a258, []int{8}
}

func (m *SparseBuckets) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SparseBuckets.Unmarshal(m, b)
}
func (m *SparseBuckets) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SparseBuckets.Marshal(b, m, deterministic)
}
func (m *SparseBuckets) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SparseBuckets.Merge(m, src)
}
func (m *SparseBuckets) XXX_Size() int {
	return xxx_messageInfo_SparseBuckets.Size(m)
}
func (m *SparseBuckets) XXX_DiscardUnknown() {
	xxx_messageInfo_SparseBuckets.DiscardUnknown(m)
}

var xxx_messageInfo_SparseBuckets proto.InternalMessageInfo

func (m *SparseBuckets) GetSpan() []*SparseBuckets_Span {
	if m != nil {
		return m.Span
	}
	return nil
}

func (m *SparseBuckets) GetDelta() []int64 {
	if m != nil {
		return m.Delta
	}
	return nil
}

func (m *SparseBuckets) GetCount() []float64 {
	if m != nil {
		return m.Count
	}
	return nil
}

type SparseBuckets_Span struct {
	Offset               *int32   `protobuf:"zigzag32,1,opt,name=offset" json:"offset,omitempty"`
	Length               *uint32  `protobuf:"varint,2,opt,name=length" json:"length,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SparseBuckets_Span) Reset()         { *m = SparseBuckets_Span{} }
func (m *SparseBuckets_Span) String() string { return proto.CompactTextString(m) }
func (*SparseBuckets_Span) ProtoMessage()    {}
func (*SparseBuckets_Span) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1e5ddb18987a258, []int{8, 0}
}

func (m *SparseBuckets_Span) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SparseBuckets_Span.Unmarshal(m, b)
}
func (m *SparseBuckets_Span) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SparseBuckets_Span.Marshal(b, m, deterministic)
}
func (m *SparseBuckets_Span) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SparseBuckets_Span.Merge(m, src)
}
func (m *SparseBuckets_Span) XXX_Size() int {
	return xxx_messageInfo_SparseBuckets_Span.Size(m)
}
func (m *SparseBuckets_Span) XXX_DiscardUnknown() {
	xxx_messageInfo_SparseBuckets_Span.DiscardUnknown(m)
}

var xxx_messageInfo_SparseBuckets_Span proto.InternalMessageInfo

func (m *SparseBuckets_Span) GetOffset() int32 {
	if m != nil && m.Offset != nil {
		return *m.Offset
	}
	return 0
}

func (m *SparseBuckets_Span) GetLength() uint32 {
	if m != nil && m.Length != nil {
		return *m.Length
	}
	return 0
}

type Exemplar struct {
	Label                []*LabelPair         `protobuf:"bytes,1,rep,name=label" json:"label,omitempty"`
	Value                *float64             `protobuf:"fixed64,2,opt,name=value" json:"value,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=timestamp" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Exemplar) Reset()         { *m = Exemplar{} }
func (m *Exemplar) String() string { return proto.CompactTextString(m) }
func (*Exemplar) ProtoMessage()    {}
func (*Exemplar) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1e5ddb18987a258, []int{9}
}

func (m *Exemplar) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Exemplar.Unmarshal(m, b)
}
func (m *Exemplar) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Exemplar.Marshal(b, m, deterministic)
}
func (m *Exemplar) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Exemplar.Merge(m, src)
}
func (m *Exemplar) XXX_Size() int {
	return xxx_messageInfo_Exemplar.Size(m)
}
func (m *Exemplar) XXX_DiscardUnknown() {
	xxx_messageInfo_Exemplar.DiscardUnknown(m)
}

var xxx_messageInfo_Exemplar proto.InternalMessageInfo

func (m *Exemplar) GetLabel() []*LabelPair {
	if m != nil {
		return m.Label
	}
	return nil
}

func (m *Exemplar) GetValue() float64 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

func (m *Exemplar) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

type Metric struct {
	Label                []*LabelPair `protobuf:"bytes,1,rep,name=label" json:"label,omitempty"`
	Gauge                *Gauge       `protobuf:"bytes,2,opt,name=gauge" json:"gauge,omitempty"`
	Counter              *Counter     `protobuf:"bytes,3,opt,name=counter" json:"counter,omitempty"`
	Summary              *Summary     `protobuf:"bytes,4,opt,name=summary" json:"summary,omitempty"`
	Untyped              *Untyped     `protobuf:"bytes,5,opt,name=untyped" json:"untyped,omitempty"`
	Histogram            *Histogram   `protobuf:"bytes,7,opt,name=histogram" json:"histogram,omitempty"`
	TimestampMs          *int64       `protobuf:"varint,6,opt,name=timestamp_ms,json=timestampMs" json:"timestamp_ms,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Metric) Reset()         { *m = Metric{} }
func (m *Metric) String() string { return proto.CompactTextString(m) }
func (*Metric) ProtoMessage()    {}
func (*Metric) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1e5ddb18987a258, []int{10}
}

func (m *Metric) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metric.Unmarshal(m, b)
}
func (m *Metric) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metric.Marshal(b, m, deterministic)
}
func (m *Metric) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metric.Merge(m, src)
}
func (m *Metric) XXX_Size() int {
	return xxx_messageInfo_Metric.Size(m)
}
func (m *Metric) XXX_DiscardUnknown() {
	xxx_messageInfo_Metric.DiscardUnknown(m)
}

var xxx_messageInfo_Metric proto.InternalMessageInfo

func (m *Metric) GetLabel() []*LabelPair {
	if m != nil {
		return m.Label
	}
	return nil
}

func (m *Metric) GetGauge() *Gauge {
	if m != nil {
		return m.Gauge
	}
	return nil
}

func (m *Metric) GetCounter() *Counter {
	if m != nil {
		return m.Counter
	}
	return nil
}

func (m *Metric) GetSummary() *Summary {
	if m != nil {
		return m.Summary
	}
	return nil
}

func (m *Metric) GetUntyped() *Untyped {
	if m != nil {
		return m.Untyped
	}
	return nil
}

func (m *Metric) GetHistogram() *Histogram {
	if m != nil {
		return m.Histogram
	}
	return nil
}

func (m *Metric) GetTimestampMs() int64 {
	if m != nil && m.TimestampMs != nil {
		return *m.TimestampMs
	}
	return 0
}

type MetricFamily struct {
	Name                 *string     `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Help                 *string     `protobuf:"bytes,2,opt,name=help" json:"help,omitempty"`
	Type                 *MetricType `protobuf:"varint,3,opt,name=type,enum=io.prometheus.client.MetricType" json:"type,omitempty"`
	Metric               []*Metric   `protobuf:"bytes,4,rep,name=metric" json:"metric,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *MetricFamily) Reset()         { *m = MetricFamily{} }
func (m *MetricFamily) String() string { return proto.CompactTextString(m) }
func (*MetricFamily) ProtoMessage()    {}
func (*MetricFamily) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1e5ddb18987a258, []int{11}
}

func (m *MetricFamily) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetricFamily.Unmarshal(m, b)
}
func (m *MetricFamily) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetricFamily.Marshal(b, m, deterministic)
}
func (m *MetricFamily) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetricFamily.Merge(m, src)
}
func (m *MetricFamily) XXX_Size() int {
	return xxx_messageInfo_MetricFamily.Size(m)
}
func (m *MetricFamily) XXX_DiscardUnknown() {
	xxx_messageInfo_MetricFamily.DiscardUnknown(m)
}

var xxx_messageInfo_MetricFamily proto.InternalMessageInfo

func (m *MetricFamily) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *MetricFamily) GetHelp() string {
	if m != nil && m.Help != nil {
		return *m.Help
	}
	return ""
}

func (m *MetricFamily) GetType() MetricType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return MetricType_COUNTER
}

func (m *MetricFamily) GetMetric() []*Metric {
	if m != nil {
		return m.Metric
	}
	return nil
}

func init() {
	proto.RegisterEnum("io.prometheus.client.MetricType", MetricType_name, MetricType_value)
	proto.RegisterType((*LabelPair)(nil), "io.prometheus.client.LabelPair")
	proto.RegisterType((*Gauge)(nil), "io.prometheus.client.Gauge")
	proto.RegisterType((*Counter)(nil), "io.prometheus.client.Counter")
	proto.RegisterType((*Quantile)(nil), "io.prometheus.client.Quantile")
	proto.RegisterType((*Summary)(nil), "io.prometheus.client.Summary")
	proto.RegisterType((*Untyped)(nil), "io.prometheus.client.Untyped")
	proto.RegisterType((*Histogram)(nil), "io.prometheus.client.Histogram")
	proto.RegisterType((*Bucket)(nil), "io.prometheus.client.Bucket")
	proto.RegisterType((*SparseBuckets)(nil), "io.prometheus.client.SparseBuckets")
	proto.RegisterType((*SparseBuckets_Span)(nil), "io.prometheus.client.SparseBuckets.Span")
	proto.RegisterType((*Exemplar)(nil), "io.prometheus.client.Exemplar")
	proto.RegisterType((*Metric)(nil), "io.prometheus.client.Metric")
	proto.RegisterType((*MetricFamily)(nil), "io.prometheus.client.MetricFamily")
}

func init() {
	proto.RegisterFile("io/prometheus/client/metrics.proto", fileDescriptor_d1e5ddb18987a258)
}

var fileDescriptor_d1e5ddb18987a258 = []byte{
	// 914 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0xdd, 0x72, 0xdb, 0x44,
	0x14, 0x46, 0xb1, 0xfc, 0xa3, 0xe3, 0x86, 0x38, 0xdb, 0x4c, 0xc7, 0x93, 0x12, 0x62, 0xc4, 0x4d,
	0xe8, 0x80, 0x3c, 0x74, 0x52, 0x60, 0x4a, 0xb9, 0x48, 0xda, 0x34, 0x65, 0x06, 0xa7, 0x61, 0x6d,
	0x5f, 0xb4, 0x5c, 0x68, 0x56, 0xf6, 0x46, 0xd6, 0xa0, 0xd5, 0x0a, 0xad, 0xd4, 0x21, 0xbc, 0x00,
	0xd7, 0xbc, 0x02, 0x6f, 0xc0, 0x4b, 0xf0, 0x0e, 0x3c, 0x0d, 0xcc, 0xfe, 0x48, 0x8a, 0x8b, 0x0c,
	0x6d, 0xef, 0x74, 0xce, 0x7e, 0xdf, 0xd1, 0xf9, 0x8e, 0x76, 0xbf, 0x15, 0xb8, 0x11, 0x1f, 0xa7,
	0x19, 0x67, 0x34, 0x5f, 0xd1, 0x42, 0x8c, 0x17, 0x71, 0x44, 0x93, 0x7c, 0xcc, 0x68, 0x9e, 0x45,
	0x0b, 0xe1, 0xa5, 0x19, 0xcf, 0x39, 0xda, 0x8b, 0xb8, 0x57, 0x63, 0x3c, 0x8d, 0xd9, 0x3f, 0x0c,
	0x39, 0x0f, 0x63, 0x3a, 0x56, 0x98, 0xa0, 0xb8, 0x1a, 0xe7, 0x11, 0xa3, 0x22, 0x27, 0x2c, 0xd5,
	0x34, 0xf7, 0x01, 0x38, 0xdf, 0x91, 0x80, 0xc6, 0x97, 0x24, 0xca, 0x10, 0x02, 0x3b, 0x21, 0x8c,
	0x0e, 0xad, 0x91, 0x75, 0xe4, 0x60, 0xf5, 0x8c, 0xf6, 0xa0, 0xfd, 0x8a, 0xc4, 0x05, 0x1d, 0x6e,
	0xa9, 0xa4, 0x0e, 0xdc, 0x03, 0x68, 0x9f, 0x93, 0x22, 0xbc, 0xb1, 0x2c, 0x39, 0x56, 0xb9, 0xfc,
	0x03, 0x74, 0x1f, 0xf3, 0x22, 0xc9, 0x69, 0xd6, 0x0c, 0x40, 0x0f, 0xa1, 0x47, 0x7f, 0xa6, 0x2c,
	0x8d, 0x49, 0xa6, 0x0a, 0xf7, 0xef, 0x7f, 0xe8, 0x35, 0x09, 0xf0, 0xce, 0x0c, 0x0a, 0x57, 0x78,
	0xf7, 0x11, 0xf4, 0xbe, 0x2f, 0x48, 0x92, 0x47, 0x31, 0x45, 0xfb, 0xd0, 0xfb, 0xc9, 0x3c, 0x9b,
	0x17, 0x54, 0xf1, 0x7a, 0xe7, 0x55, 0x6b, 0xbf, 0x5a, 0xd0, 0x9d, 0x16, 0x8c, 0x91, 0xec, 0x1a,
	0x7d, 0x04, 0xb7, 0x04, 0x61, 0x69, 0x4c, 0xfd, 0x85, 0xec, 0x56, 0x55, 0xb0, 0x71, 0x5f, 0xe7,
	0x94, 0x00, 0x74, 0x00, 0x60, 0x20, 0xa2, 0x60, 0xa6, 0x92, 0xa3, 0x33, 0xd3, 0x82, 0x49, 0x1d,
	0xd5, 0xfb, 0x5b, 0xa3, 0xd6, 0x66, 0x1d, 0x65, 0xc7, 0x75, 0x7f, 0xee, 0x21, 0x74, 0xe7, 0x49,
	0x7e, 0x9d, 0xd2, 0xe5, 0x86, 0x29, 0xfe, 0xd5, 0x02, 0xe7, 0x59, 0x24, 0x72, 0x1e, 0x66, 0x84,
	0xbd, 0x49, 0xb3, 0x9f, 0x02, 0xba, 0x09, 0xf1, 0xaf, 0x62, 0x4e, 0xf2, 0xa1, 0xa3, 0x6a, 0x0e,
	0x6e, 0x00, 0x9f, 0xca, 0xfc, 0xff, 0x49, 0x3b, 0x86, 0x4e, 0x50, 0x2c, 0x7e, 0xa4, 0xb9, 0x11,
	0xf6, 0x41, 0xb3, 0xb0, 0x53, 0x85, 0xc1, 0x06, 0x8b, 0xee, 0x82, 0x23, 0x02, 0x5f, 0x2c, 0x56,
	0x94, 0x91, 0xa1, 0x3d, 0xb2, 0x8e, 0x76, 0x71, 0x4f, 0x04, 0x53, 0x15, 0xa3, 0x7b, 0xb0, 0x2b,
	0x02, 0xff, 0x17, 0x9a, 0x71, 0x3f, 0x5f, 0x65, 0x54, 0xac, 0x78, 0xbc, 0x1c, 0xb6, 0xd5, 0x8b,
	0x77, 0x44, 0xf0, 0x92, 0x66, 0x7c, 0x56, 0xa6, 0x91, 0x0b, 0xdb, 0x25, 0x56, 0xeb, 0xed, 0x18,
	0xbd, 0x0a, 0xa7, 0xf5, 0x7e, 0x06, 0xb7, 0xd7, 0x30, 0x46, 0x30, 0x18, 0xc1, 0x35, 0x52, 0x0b,
	0x7e, 0x02, 0x7d, 0x11, 0xf8, 0x09, 0x0d, 0x49, 0x1e, 0xbd, 0xa2, 0xc3, 0xae, 0xda, 0x77, 0x1f,
	0x37, 0xcb, 0x9a, 0xa6, 0x24, 0x13, 0x54, 0x8b, 0x13, 0x18, 0x44, 0x70, 0x61, 0x68, 0xa6, 0x4a,
	0xca, 0x45, 0xa4, 0xaa, 0xf4, 0xde, 0xaa, 0xca, 0xa5, 0xa1, 0xb9, 0x7f, 0x5a, 0xd0, 0xd1, 0x79,
	0xf4, 0x09, 0x0c, 0x16, 0x05, 0x2b, 0x62, 0x55, 0x7e, 0xed, 0xe3, 0xee, 0xd4, 0x79, 0x2d, 0xf8,
	0x18, 0xee, 0xbc, 0x0e, 0x35, 0x9a, 0x6d, 0xa5, 0x79, 0xef, 0x35, 0x82, 0xd6, 0x7d, 0x08, 0xfd,
	0x22, 0x4d, 0x69, 0xe6, 0x07, 0xbc, 0x48, 0x96, 0xe6, 0x4b, 0x83, 0x4a, 0x9d, 0xca, 0xcc, 0xda,
	0x69, 0x6c, 0xbd, 0xe5, 0x69, 0xfc, 0xc3, 0x82, 0xed, 0x35, 0x99, 0xe8, 0x11, 0xd8, 0x22, 0x25,
	0xc9, 0xd0, 0x52, 0xdb, 0xe6, 0xe8, 0x0d, 0x26, 0x23, 0xa3, 0x04, 0x2b, 0x96, 0x3c, 0x0a, 0x4b,
	0x1a, 0xe7, 0x64, 0xb8, 0x35, 0x6a, 0x1d, 0x21, 0xac, 0x03, 0x99, 0xd5, 0x83, 0x91, 0x7b, 0xd1,
	0xc2, 0x3a, 0xd8, 0xff, 0x02, 0x6c, 0xc9, 0x44, 0x77, 0xa0, 0xc3, 0xaf, 0xae, 0x04, 0xd5, 0x73,
	0xdb, 0xc5, 0x26, 0x92, 0xf9, 0x98, 0x26, 0x61, 0xbe, 0x52, 0x9a, 0xb7, 0xb1, 0x89, 0xdc, 0xdf,
	0x2c, 0xe8, 0x95, 0x52, 0xd0, 0x03, 0x68, 0xc7, 0xd2, 0x01, 0x4d, 0xbf, 0x87, 0xcd, 0xfd, 0x56,
	0x26, 0x89, 0x35, 0xba, 0xd9, 0x5d, 0xd0, 0x57, 0xe0, 0x54, 0x0e, 0x6b, 0x46, 0xb9, 0xef, 0x69,
	0x0f, 0xf6, 0x4a, 0x0f, 0xf6, 0x66, 0x25, 0x02, 0xd7, 0x60, 0xf7, 0xef, 0x2d, 0xe8, 0x4c, 0x94,
	0xa3, 0xbf, 0x6b, 0x47, 0x9f, 0x43, 0x3b, 0x94, 0x9e, 0x6c, 0x0c, 0xf5, 0x6e, 0x33, 0x4d, 0xd9,
	0x36, 0xd6, 0x48, 0xf4, 0x25, 0x74, 0x17, 0xda, 0xa7, 0x4d, 0xb3, 0x07, 0xcd, 0x24, 0x63, 0xe6,
	0xb8, 0x44, 0x4b, 0xa2, 0xd0, 0x26, 0xaa, 0x76, 0xde, 0x46, 0xa2, 0x71, 0x5a, 0x5c, 0xa2, 0x25,
	0xb1, 0xd0, 0xa6, 0xa7, 0x0e, 0xfe, 0x46, 0xa2, 0x71, 0x46, 0x5c, 0xa2, 0xd1, 0x37, 0xe0, 0xac,
	0x4a, 0x2f, 0x34, 0x47, 0x77, 0xc3, 0x60, 0x2a, 0xcb, 0xc4, 0x35, 0x43, 0xba, 0x67, 0x35, 0x6b,
	0x9f, 0x09, 0xe5, 0x26, 0x2d, 0xdc, 0xaf, 0x72, 0x13, 0xe1, 0xfe, 0x6e, 0xc1, 0x2d, 0xfd, 0x05,
	0x9e, 0x12, 0x16, 0xc5, 0xd7, 0x8d, 0xd7, 0x21, 0x02, 0x7b, 0x45, 0xe3, 0xd4, 0xdc, 0x86, 0xea,
	0x19, 0x1d, 0x83, 0x2d, 0x7b, 0x54, 0x23, 0x7c, 0xff, 0xfe, 0xa8, 0xb9, 0x2b, 0x5d, 0x79, 0x76,
	0x9d, 0x52, 0xac, 0xd0, 0xd2, 0x5f, 0xf5, 0x0d, 0x3e, 0xb4, 0xff, 0xcb, 0x5f, 0x35, 0x0f, 0x1b,
	0xec, 0xbd, 0x00, 0xa0, 0xae, 0x84, 0xfa, 0xd0, 0x7d, 0xfc, 0x7c, 0x7e, 0x31, 0x3b, 0xc3, 0x83,
	0xf7, 0x90, 0x03, 0xed, 0xf3, 0x93, 0xf9, 0xf9, 0xd9, 0xc0, 0x92, 0xf9, 0xe9, 0x7c, 0x32, 0x39,
	0xc1, 0x2f, 0x06, 0x5b, 0x32, 0x98, 0x5f, 0xcc, 0x5e, 0x5c, 0x9e, 0x3d, 0x19, 0xb4, 0xd0, 0x36,
	0x38, 0xcf, 0xbe, 0x9d, 0xce, 0x9e, 0x9f, 0xe3, 0x93, 0xc9, 0xc0, 0x46, 0xb7, 0x61, 0x47, 0x71,
	0xfc, 0x3a, 0xd9, 0x3e, 0xc5, 0xd0, 0xf8, 0x33, 0xf1, 0xf2, 0x61, 0x18, 0xe5, 0xab, 0x22, 0xf0,
	0x16, 0x9c, 0xfd, 0xfb, 0x77, 0xc4, 0x67, 0x7c, 0x49, 0xe3, 0x71, 0xc8, 0xbf, 0x8e, 0xb8, 0x5f,
	0xaf, 0xfa, 0x7a, 0xf5, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x48, 0x31, 0xb7, 0xd8, 0xc3, 0x08,
	0x00, 0x00,
}
